version: '3.5'
name: hitl-backend
services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    restart: 'no'
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 7999:8080
